// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: protos/messagesave.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerId  int32  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Id       int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Category string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *MessageSaveRequest) Reset() {
	*x = MessageSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_messagesave_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSaveRequest) ProtoMessage() {}

func (x *MessageSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messagesave_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSaveRequest.ProtoReflect.Descriptor instead.
func (*MessageSaveRequest) Descriptor() ([]byte, []int) {
	return file_protos_messagesave_proto_rawDescGZIP(), []int{0}
}

func (x *MessageSaveRequest) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *MessageSaveRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageSaveRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type MessageSaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *MessageSaveResponse) Reset() {
	*x = MessageSaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_messagesave_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSaveResponse) ProtoMessage() {}

func (x *MessageSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messagesave_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSaveResponse.ProtoReflect.Descriptor instead.
func (*MessageSaveResponse) Descriptor() ([]byte, []int) {
	return file_protos_messagesave_proto_rawDescGZIP(), []int{1}
}

func (x *MessageSaveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_protos_messagesave_proto protoreflect.FileDescriptor

var file_protos_messagesave_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x61, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x12, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x2f, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x4e, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x53, 0x61, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38,
	0x0a, 0x0b, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x13, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x61, 0x76, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x64, 0x73, 0x2f, 0x76,
	0x6b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_messagesave_proto_rawDescOnce sync.Once
	file_protos_messagesave_proto_rawDescData = file_protos_messagesave_proto_rawDesc
)

func file_protos_messagesave_proto_rawDescGZIP() []byte {
	file_protos_messagesave_proto_rawDescOnce.Do(func() {
		file_protos_messagesave_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_messagesave_proto_rawDescData)
	})
	return file_protos_messagesave_proto_rawDescData
}

var file_protos_messagesave_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_messagesave_proto_goTypes = []interface{}{
	(*MessageSaveRequest)(nil),  // 0: MessageSaveRequest
	(*MessageSaveResponse)(nil), // 1: MessageSaveResponse
}
var file_protos_messagesave_proto_depIdxs = []int32{
	0, // 0: MessageSaveService.SaveMessage:input_type -> MessageSaveRequest
	1, // 1: MessageSaveService.SaveMessage:output_type -> MessageSaveResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_messagesave_proto_init() }
func file_protos_messagesave_proto_init() {
	if File_protos_messagesave_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_messagesave_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_messagesave_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_messagesave_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_messagesave_proto_goTypes,
		DependencyIndexes: file_protos_messagesave_proto_depIdxs,
		MessageInfos:      file_protos_messagesave_proto_msgTypes,
	}.Build()
	File_protos_messagesave_proto = out.File
	file_protos_messagesave_proto_rawDesc = nil
	file_protos_messagesave_proto_goTypes = nil
	file_protos_messagesave_proto_depIdxs = nil
}
