name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Login to heroku registry"
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:login

      - name: "Build and push to heroku registry"
        run: heroku container:push web --app ${{secrets.HEROKU_APP_NAME}}

      - name: "Releases the container"
        run: heroku container:release web --app ${{secrets.HEROKU_APP_NAME}}
